### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by aboks**
Adds PHP support, as described in #20.

With these changes, the new minimum versions become:
* v7.1 or higher for PHP. Supporting a lower version does not seem possible with the same code, as newer PHPUnit versions need the `void` type on the `setUp`-method, which is only available as of 7.1.
* v14 for `webonyx/graphql-php`

I would recommend to release these changes as a v0.6 or v1.0, so that people who need support for older versions can stay on the 0.5-series.

The Travis CI job currently passes for PHP 7.1, 7.2, 7.3, 7.4, 8.0 and the nightly build. The HHVM job fails, as apparently Composer does not work anymore on HHVM. I would recommend to drop HHVM from the Travis matrix.

### CODE REVIEW

**Comment by aboks** [comment]
@ivome did you already have a chance to take a look at this?

**Comment by ivome** [comment]
Thanks for adding support for this @aboks and sorry for the delay! I just merged this and created a new release v0.6.0.

**Comment by aboks** [comment]
Great! Don't worry about the delay, thanks for creating and maintaining this in your spare time.

**Comment by aboks** [comment]
@ivome Oh, one more thing: it seems the new 0.6.0 version is not on Packagist yet. You probably need to either trigger a manual update and/or set up synchronization hooks. See https://packagist.org/about#how-to-update-packages.

**Comment by ivome** [comment]
@aboks Done! This should be available on Packagist now.

**Pull request merged**
